import React from "react";
import LegalPage from "./LegalPage";
import type { LegalSection } from "./LegalPage";
import { useLocale } from "../../contexts/LocaleContext";

const LAST_UPDATED = "June 16, 2026";

const Terms: React.FC = () => {
  const { t } = useLocale();

  const sections: LegalSection[] = [
    {
      heading: t("Acceptance of these terms"),
      body: [
        t(
          "SigmaLoop is a personalized AI tutor for programming and mathematics. By creating an account, talking to the mentor, or otherwise using the service, you agree to these Terms of Service. If you do not agree, please do not use SigmaLoop."
        ),
        t(
          "If you are using SigmaLoop on behalf of a school or organization, you confirm that you are authorized to accept these terms on its behalf."
        ),
      ],
    },
    {
      heading: t("What SigmaLoop provides"),
      body: [
        t(
          "Every course, lesson, challenge, and test case you see is generated by an AI pipeline specifically for you — there is no shared catalog and no instructor-authored content. The mentor can read your own courses and progress and, at your request, create or modify your learning material."
        ),
        t(
          "Because the content is generated, it may contain mistakes. SigmaLoop is a study aid, not a substitute for professional instruction, certification, or your own judgement. Always verify important information independently."
        ),
      ],
    },
    {
      heading: t("Your account"),
      body: [
        t(
          "You are responsible for the activity on your account and for keeping your password secure. Provide accurate information when you register, and let us know promptly if you suspect unauthorized access. One person may not share a single account with others in a way that misrepresents who is learning."
        ),
      ],
    },
    {
      heading: t("Acceptable use"),
      body: [
        t(
          "You agree to use SigmaLoop only for lawful, educational purposes. You may not:"
        ),
      ],
      bullets: [
        t(
          "Attempt to break, overload, reverse-engineer, or gain unauthorized access to the service or its AI providers."
        ),
        t(
          "Use the mentor or generation pipeline to produce unlawful, harassing, or abusive content, or to facilitate academic dishonesty in violation of your institution's rules."
        ),
        t(
          "Scrape, resell, or redistribute generated content or test cases as if they were a public dataset or product."
        ),
        t("Submit code intended to harm the execution sandbox or other users."),
      ],
    },
    {
      heading: t("AI-generated content and grading"),
      body: [
        t(
          "Programming challenges are graded by running your code against AI-generated test cases in a sandbox; multiple-choice questions are graded deterministically on our servers; and math answers are evaluated by an AI grader that returns a structured verdict. Automated grading can be wrong, and low-confidence math verdicts are surfaced as 'pending review' rather than a final result."
        ),
        t(
          "You retain ownership of the code and answers you submit. You grant SigmaLoop the limited right to process them — including sending them to our AI providers — solely to operate features such as grading, hints, and progress tracking."
        ),
      ],
    },
    {
      heading: t("Availability and changes"),
      body: [
        t(
          "SigmaLoop is offered on an 'as is' and 'as available' basis. We may add, change, or remove features, and generation or grading may occasionally be delayed or unavailable. We may update these terms from time to time; material changes will be reflected by the 'last updated' date above, and continued use after a change means you accept the revised terms."
        ),
      ],
    },
    {
      heading: t("Limitation of liability"),
      body: [
        t(
          "To the fullest extent permitted by law, SigmaLoop and its maintainers are not liable for any indirect, incidental, or consequential damages, or for any loss arising from reliance on AI-generated content or automated grading. Your use of the service is at your own discretion and risk."
        ),
      ],
    },
    {
      heading: t("Termination"),
      body: [
        t(
          "You may stop using SigmaLoop at any time and delete your account and all associated content from Settings. We may suspend or terminate access that violates these terms or that puts the service or other learners at risk."
        ),
      ],
    },
    {
      heading: t("Contact"),
      body: [
        t(
          "Questions about these terms? Reach us through the Contact page or at support@sigmaloop.app."
        ),
      ],
    },
  ];

  return (
    <LegalPage
      title={t("Terms of Service")}
      updated={LAST_UPDATED}
      intro={t(
        "These terms govern your use of SigmaLoop. We've kept them short and readable — please take a moment to look them over."
      )}
      sections={sections}
    />
  );
};

export default Terms;
